baseURL = "https://slenk.com/"
languageCode = "en-us"
title = "Slenk Network"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
#googleAnalytics = ""

[params]
    author = "Derek Slenk"
    description = "Personal blog theme powered by Hugo"
    githubUsername = "derekslenk"
    accent = "#f5841a"
    linkColor = "#3e4b5e"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = false
    backgroundImg = "slenk-logo-horizontal.svg"
#    highlightStyle = "default"
#    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 10

[[menu.main]]
    url = "/public-services/"
    name = "Public Services"
    weight = 20

[[menu.main]]
    url = "https://mail.slenk.email/"
    name = "Mailcow"
    weight = 30


#[[menu.main]]
#    url = "/project/"
#    name = "Projects"
#    weight = 1000

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:site@slenk.com"
    name = "envelope-o"
    weight = 1

#[[menu.icon]]
#    url = "https://github.com/username/"
#    name = "github"
#    weight = 2

#[[menu.icon]]
#    url = "https://twitter.com/username/"
#    name = "twitter"
#    weight = 3

#[[menu.icon]]
#    url = "https://www.linkedin.com/in/username/"
#    name = "linkedin"
#    weight = 4

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "stack-overflow"
#    weight = 5


theme = ["plausible-hugo"]  # Add this theme to your already existing other themes
[params.plausible]
  enable = true  # Whether to enable plausible tracking
  selfhosted_domain = "analytics.slenk.com" 
  domain = "slenk.com"  # Plausible "domain" name/id in your dashboard
